### ISSUE TITLE
Support for Flink 1.2

### ISSUE THREAD

**Issue by affo** [ottogroup/flink-spector#35]
Hello, I was trying to use flink-spector together with Flink 1.2, but the test hangs up indefinitely while running. I switched back to 1.1.4 and everything is ok.

Is this because of lack of 1.2 support? Are you planning to support it?

Thank you

**Comment by radcheb** [comment]
+1

**Comment by bowenli86** [comment]
+1. Any update on future support of Flink releases?

**Comment by shvimal06** [comment]
+1

**Comment by lofifnc** [comment]
I will see into this on the Weekend!
There have been Plans to contribute back but I haven't followed trough.

**Comment by lofifnc** [comment]
Maven artifacts for 1.2 support have been published!
Please provide some feedback if your issues have been resolved.

**Comment by bowenli86** [comment]
@lofifnc Hi Alex, since I haven't heard back from you for a few days, I thought you were not maintaining it, and forked your code at https://github.com/bowenli86/flink-spector . It makes Java APIs work with Flink 1.2.

What's your plan on flink-spector? Given its huge value, do you think that move it out of ottogroup and make it an independent project will ease management of the project and open more opportunities for community contribution?

**Comment by lofifnc** [comment]
@bowenli86 I have been in China and had problems with maintaining my usual communication channels. Feel free to open a pull request if you have anything interesting. 

I can't think of a reason to move it out of ottogroup as it's just a formality. It's open for contribution and were also willing to contribute it back to the core project. 

The top priority right now for me is to provide basic support for a Scala API.
