### ISSUE TITLE
Tests don't work while making mvn test on CircleCI

### ISSUE THREAD

**Issue by Sefirq** [ottogroup/flink-spector#66]
Hello,

I encountered a problem. On my machine, when I create tests and run them with mvn test, all of them are passed, but when I build on CircleCI, project compiles, all dependencies are resolved, but all the tests are failed and instead of any results, I get:

    testClientSexCounter(FlinkOperationsTest)  Time elapsed: 2.138 sec  <<< FAILURE!
    java.lang.AssertionError: 
    Expected: output ( contains all <List((F,1), (M,1), (F,2))>) 
         but: was <[]>

Is there an issue with tests from such services?

Best Regards

Sefirq

**Comment by lofifnc** [comment]
Hi,

We're running test on Jenkins and TravisCI. The only issue we've encounter so far is that tests run slower than on the local machine and we had to increase some timeouts.
But this doesn't seem to be the issue here.

As I've never used CircleCI I've tried to run some tests there and everything works fine.
Are you able to post the necessary steps to recreate this problem?

**Comment by Sefirq** [comment]
Never mind, actually I didn't change absolute path to relative in one file.

Please, remember about it, other such stupid people as myself!
