### ISSUE TITLE
setParallelism changes test outcome

### ISSUE THREAD

**Issue by haf** [ottogroup/flink-spector#92]
I have a test case that passes when I run with `setParallelism(1)` but fails with e.g. `setParallelism(4)`;

The test case looks like this:

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/193115/56614976-78993480-661a-11e9-85e5-28cc413f56b3.png">

None of the tests are dependent on any other data source nor stream, than the input stream that the test supplies.

So I'm a bit confounded as to why parallelism might cause a different test outcome? Flink 1.7.2 on JDK 8, here.

I added some `println` statements at the last output node and it prints the correct values; only the test sink fails to receive the events.

**Comment by lofifnc** [comment]
Any parallelism greater than one will remove determinism from the test run. Because the events are now processed in parallel by multiple instances of the operators. For example the order of the events is not predefined any more. If I interpret your test correctly no expectation is checking the order of events. It could be the case, that the logic you're testing depends on order, or that a certain instance of a function sees certain events.
Without more information it's hard to say what's the case. I hope this helps.

**Comment by haf** [comment]
@lofifnc Thank you for your reply. I have nothing that requires a deterministic ordering, but I have a `keyBy` operator in there as well as a `BoundedOutOfOrderTimestampExtractor`. In fact, all of the code fits in this screengrab:

![image](https://user-images.githubusercontent.com/193115/56644602-4c160480-667c-11e9-8946-4b4a256da691.png)

When `setParallelism(2)` is run, the matcher gets zero output events, but like you can see I have a println in a `map`, which gets run with parallelism enabled; and it outputs the correct value... I'm at a bit of a loss as to why the asserter would get zero values...

**Comment by lofifnc** [comment]
I have been successful in recreating your problem and found a fix for it. #93 I'm going to release it and wait for your confirmation.

**Comment by lofifnc** [comment]
Version 0.9.3 has been released. Can you confirm this resolves your issue?

**Comment by haf** [comment]
Thank you very much, I'm going to try it tomorrow morning first thing!

**Comment by haf** [comment]
@lofifnc I didn't make it "first thing" but I've tried it now, and it works perfectly! Thank you @lofifnc
